version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      # - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mqtt-debug:
    image: eclipse-mosquitto:2
    container_name: mqtt-debug
    depends_on:
      - mosquitto
    env_file:
      - ./secrets/mqtt-debug.env
    command: >
      sh -c "sleep 3 &&
      mosquitto_sub
      -h mosquitto
      -p 1883
      -u $$MQTT_USERNAME
      -P $$MQTT_PASSWORD
      -t 'factory/#'
      -v"
